import "server-only";

import { createClient } from "@/lib/supabase/server";
import { supabaseConfigured } from "@/lib/env";
import type { BarnEvent } from "@/lib/types";

/**
 * Barn calendar reads.
 *
 * Not filtered by visibility here: the RLS policy already gives a family only
 * the entries marked visible to everyone, so a parent asking for "all events"
 * receives exactly the public ones. Filtering again in the app would put the
 * rule in two places and let them drift.
 */
export async function listUpcomingEvents(limit = 50): Promise<BarnEvent[]> {
  if (!supabaseConfigured()) return [];

  const supabase = await createClient();
  const { data, error } = await supabase
    .from("events")
    .select("*")
    .gte("start_at", new Date().toISOString())
    .order("start_at", { ascending: true })
    .limit(limit);

  if (error) return [];
  return (data ?? []) as BarnEvent[];
}

export async function listAllEvents(): Promise<BarnEvent[]> {
  if (!supabaseConfigured()) return [];

  const supabase = await createClient();
  const { data, error } = await supabase
    .from("events")
    .select("*")
    .order("start_at", { ascending: false });

  if (error) return [];
  return (data ?? []) as BarnEvent[];
}

/**
 * Split the calendar into what is still to come and what has been.
 *
 * The "now" lives here rather than in the page because calling `Date.now()`
 * inline during render is an impure call in a component — React's rules ban it,
 * and the lint enforces that. A module function is the right home for it.
 */
/**
 * Events overlapping a window, for the calendar.
 *
 * `start_at` is a timestamptz, so the bounds are widened by a day either side
 * and the exact barn-local day is decided in the aggregator. Comparing a
 * timestamp to a bare date in SQL would silently use UTC, which is how an
 * 8pm event lands on tomorrow's grid for a barn in New York.
 */
export async function listEventsBetween(from: string, through: string): Promise<BarnEvent[]> {
  if (!supabaseConfigured()) return [];

  const supabase = await createClient();
  const { data, error } = await supabase
    .from("events")
    .select("*")
    .gte("start_at", `${from}T00:00:00Z`)
    .lte("start_at", `${through}T23:59:59Z`)
    .order("start_at", { ascending: true });

  if (error) return [];
  return (data ?? []) as BarnEvent[];
}

export function partitionEvents(events: BarnEvent[]): {
  upcoming: BarnEvent[];
  past: BarnEvent[];
} {
  const now = Date.now();
  const upcoming: BarnEvent[] = [];
  const past: BarnEvent[] = [];

  for (const event of events) {
    if (new Date(event.start_at).getTime() >= now) upcoming.push(event);
    else past.push(event);
  }

  upcoming.sort((a, b) => a.start_at.localeCompare(b.start_at));
  past.sort((a, b) => b.start_at.localeCompare(a.start_at));

  return { upcoming, past };
}

/**
 * This user's calendar subscription token, minting one if they have none.
 *
 * Read-your-own only — not even the admin can read someone else's (migration
 * 0014), because the token is a bearer credential: whoever holds it can read
 * that person's schedule with no session at all.
 */
export async function myCalendarToken(profileId: string): Promise<string | null> {
  if (!supabaseConfigured()) return null;

  const supabase = await createClient();

  const { data: existing } = await supabase
    .from("ical_tokens")
    .select("token")
    .eq("profile_id", profileId)
    .maybeSingle();

  if (existing?.token) return existing.token as string;

  // The token column is generated by the database and overwritten by the guard
  // trigger, so nothing here chooses it.
  const { data, error } = await supabase
    .from("ical_tokens")
    .insert({ profile_id: profileId })
    .select("token")
    .single();

  if (error) return null;
  return (data?.token as string) ?? null;
}
